INSERT INTO THEME (ID, NAME, DESCRIPTION, PRICE) VALUES (1,'theme1', 'desc1', 10000);
INSERT INTO THEME (ID, NAME, DESCRIPTION, PRICE) VALUES (2,'theme2', 'desc2', 20000);
INSERT INTO THEME (ID, NAME, DESCRIPTION, PRICE) VALUES (3,'theme3', 'desc3', 30000);
INSERT INTO THEME (ID, NAME, DESCRIPTION, PRICE) VALUES (4,'theme4', 'desc4', 40000);
INSERT INTO SCHEDULE (ID, THEME_ID, DATE, TIME) VALUES (1, 1, '2022-02-01', '11:00:00');
INSERT INTO SCHEDULE (ID, THEME_ID, DATE, TIME) VALUES (2, 2, '2022-02-02', '12:00:00');
INSERT INTO SCHEDULE (ID, THEME_ID, DATE, TIME) VALUES (3, 3, '2022-02-03', '13:00:00');
INSERT INTO SCHEDULE (ID, THEME_ID, DATE, TIME) VALUES (4, 4, '2022-02-04', '14:00:00');
INSERT INTO SCHEDULE (ID, THEME_ID, DATE, TIME) VALUES (5, 5, '2022-02-05', '15:00:00');
INSERT INTO MEMBER (ID, USERNAME, PASSWORD, NAME, PHONE, ROLE) VALUES (1, 'username1', 'user1pw', 'name1', '1', 'MEMBER');
INSERT INTO MEMBER (ID, USERNAME, PASSWORD, NAME, PHONE, ROLE) VALUES (2, 'username2', 'user2pw', 'name2', '2', 'MEMBER');
INSERT INTO MEMBER (ID, USERNAME, PASSWORD, NAME, PHONE, ROLE) VALUES (3, 'username3', 'user3pw', 'name3', '3', 'MEMBER');
INSERT INTO MEMBER (ID, USERNAME, PASSWORD, NAME, PHONE, ROLE) VALUES (4, 'username4', 'user4pw', 'name4', '4', 'MEMBER');
INSERT INTO MEMBER (ID, USERNAME, PASSWORD, NAME, PHONE, ROLE) VALUES (5, 'username5', 'user5pw', 'name5', '5', 'MEMBER');
INSERT INTO MEMBER (ID, USERNAME, PASSWORD, NAME, PHONE, ROLE) VALUES (6, 'username6', 'user6pw', 'name6', '6', 'MEMBER');
-- h2
ALTER TABLE THEME ALTER COLUMN ID RESTART WITH 5;
ALTER TABLE SCHEDULE ALTER COLUMN ID RESTART WITH 6;
ALTER TABLE MEMBER ALTER COLUMN ID RESTART WITH 7;
